[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "wasm32-unknown-unknown" },
    { triple = "wasm32-wasip1" },
    { triple = "i686-linux-android" },
    { triple = "x86_64-linux-android" },
    { triple = "armv7-linux-androideabi" },
    { triple = "aarch64-linux-android" },
    { triple = "aarch64-apple-ios" },
]
all-features = true

[advisories]
version = 2

[bans]
multiple-versions = "allow"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
required-git-spec = "rev"

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
]
