// Code generated by addchain. Do not edit.

use crate::fields::FieldElement;

/// Exponentiates a field element to a constant power.
///
/// This is used to either exponentiate field elements to the power (|F| - 2), in order to compute
/// multiplicative inverses in constant time, or to the power (p + 1) / 4, in order to compute
/// square roots in certain fields in constant time.
#[allow(unused_mut)]
pub(crate) fn exp<F: FieldElement>(x: F) -> F {
    // This is implemented with addition chain exponentiation, using the following chain:
    //
    //   _10      = 2*1
    //   _11      = 1 + _10
    //   _110     = 2*_11
    //   _111     = 1 + _110
    //   _111000  = _111 << 3
    //   _111111  = _111 + _111000
    //   _1111110 = 2*_111111
    //   _1111111 = 1 + _1111110
    //   x12      = _1111110 << 5 + _111111
    //   x24      = x12 << 12 + x12
    //   i36      = x24 << 7
    //   x31      = _1111111 + i36
    //   x48      = i36 << 17 + x24
    //   x96      = x48 << 48 + x48
    //   x127     = x96 << 31 + x31
    //   return     2*x127
    //
    // Operations: 127 squares and 10 multiplications.
    //
    // Generated by github.com/mmcloughlin/addchain v0.4.0.

    let mut t0;
    let mut t1;
    let mut z;

    // Step 1: t0 = x^0x2
    t0 = x.square();

    // Step 2: t0 = x^0x3
    t0 = x * t0;

    // Step 3: t0 = x^0x6
    t0 = t0.square();

    // Step 4: t0 = x^0x7
    t0 = x * t0;

    // Step 7: t1 = x^0x38
    t1 = t0.square();
    for _ in 1..3 {
        t1 = t1.square();
    }

    // Step 8: t0 = x^0x3f
    t0 *= t1;

    // Step 9: t1 = x^0x7e
    t1 = t0.square();

    // Step 10: z = x^0x7f
    z = x * t1;

    // Step 15: t1 = x^0xfc0
    for _ in 0..5 {
        t1 = t1.square();
    }

    // Step 16: t0 = x^0xfff
    t0 *= t1;

    // Step 28: t1 = x^0xfff000
    t1 = t0.square();
    for _ in 1..12 {
        t1 = t1.square();
    }

    // Step 29: t0 = x^0xffffff
    t0 *= t1;

    // Step 36: t1 = x^0x7fffff80
    t1 = t0.square();
    for _ in 1..7 {
        t1 = t1.square();
    }

    // Step 37: z = x^0x7fffffff
    z *= t1;

    // Step 54: t1 = x^0xffffff000000
    for _ in 0..17 {
        t1 = t1.square();
    }

    // Step 55: t0 = x^0xffffffffffff
    t0 *= t1;

    // Step 103: t1 = x^0xffffffffffff000000000000
    t1 = t0.square();
    for _ in 1..48 {
        t1 = t1.square();
    }

    // Step 104: t0 = x^0xffffffffffffffffffffffff
    t0 *= t1;

    // Step 135: t0 = x^0x7fffffffffffffffffffffff80000000
    for _ in 0..31 {
        t0 = t0.square();
    }

    // Step 136: z = x^0x7fffffffffffffffffffffffffffffff
    z *= t0;

    // Step 137: z = x^0xfffffffffffffffffffffffffffffffe
    z = z.square();

    z
}
