// Code generated by addchain. Do not edit.

use crate::fields::FieldElement;

/// Exponentiates a field element to a constant power.
///
/// This is used to either exponentiate field elements to the power (|F| - 2), in order to compute
/// multiplicative inverses in constant time, or to the power (p + 1) / 4, in order to compute
/// square roots in certain fields in constant time.
#[allow(unused_mut)]
pub(crate) fn exp<F: FieldElement>(x: F) -> F {
    // This is implemented with addition chain exponentiation, using the following chain:
    //
    //   _10       = 2*1
    //   _11       = 1 + _10
    //   _1100     = _11 << 2
    //   _1111     = _11 + _1100
    //   _11110000 = _1111 << 4
    //   _11111111 = _1111 + _11110000
    //   x16       = _11111111 << 8 + _11111111
    //   x32       = x16 << 16 + x16
    //   return      ((x32 << 32 + 1) << 96 + 1) << 94
    //
    // Operations: 253 squares and 7 multiplications.
    //
    // Generated by github.com/mmcloughlin/addchain v0.4.0.

    let mut t0;
    let mut t1;
    let mut z;

    // Step 1: t0 = x^0x2
    t0 = x.square();

    // Step 2: t0 = x^0x3
    t0 = x * t0;

    // Step 4: t1 = x^0xc
    t1 = t0.square();
    for _ in 1..2 {
        t1 = t1.square();
    }

    // Step 5: t0 = x^0xf
    t0 *= t1;

    // Step 9: t1 = x^0xf0
    t1 = t0.square();
    for _ in 1..4 {
        t1 = t1.square();
    }

    // Step 10: t0 = x^0xff
    t0 *= t1;

    // Step 18: t1 = x^0xff00
    t1 = t0.square();
    for _ in 1..8 {
        t1 = t1.square();
    }

    // Step 19: t0 = x^0xffff
    t0 *= t1;

    // Step 35: t1 = x^0xffff0000
    t1 = t0.square();
    for _ in 1..16 {
        t1 = t1.square();
    }

    // Step 36: t0 = x^0xffffffff
    t0 *= t1;

    // Step 68: t0 = x^0xffffffff00000000
    for _ in 0..32 {
        t0 = t0.square();
    }

    // Step 69: t0 = x^0xffffffff00000001
    t0 = x * t0;

    // Step 165: t0 = x^0xffffffff00000001000000000000000000000000
    for _ in 0..96 {
        t0 = t0.square();
    }

    // Step 166: z = x^0xffffffff00000001000000000000000000000001
    z = x * t0;

    // Step 260: z = x^0x3fffffffc0000000400000000000000000000000400000000000000000000000
    for _ in 0..94 {
        z = z.square();
    }

    z
}
