// Code generated by addchain. Do not edit.

use crate::fields::FieldElement;

/// Exponentiates a field element to a constant power.
///
/// This is used to either exponentiate field elements to the power (|F| - 2), in order to compute
/// multiplicative inverses in constant time, or to the power (p + 1) / 4, in order to compute
/// square roots in certain fields in constant time.
#[allow(unused_mut)]
pub(crate) fn exp<F: FieldElement>(x: F) -> F {
    // This is implemented with addition chain exponentiation, using the following chain:
    //
    //   _10       = 2*1
    //   _100      = 2*_10
    //   _101      = 1 + _100
    //   _110      = 1 + _101
    //   _1001     = _100 + _101
    //   _1111     = _110 + _1001
    //   _10010    = 2*_1001
    //   _10101    = _110 + _1111
    //   _11000    = _110 + _10010
    //   _11010    = _10 + _11000
    //   _101111   = _10101 + _11010
    //   _111000   = _1001 + _101111
    //   _111101   = _101 + _111000
    //   _111111   = _10 + _111101
    //   _1001111  = _10010 + _111101
    //   _1100001  = _10010 + _1001111
    //   _1100011  = _10 + _1100001
    //   _1110011  = _10010 + _1100001
    //   _1110111  = _100 + _1110011
    //   _1111101  = _110 + _1110111
    //   _10010101 = _11000 + _1111101
    //   _10100111 = _10010 + _10010101
    //   _10101101 = _110 + _10100111
    //   _11100101 = _111000 + _10101101
    //   _11111111 = _11010 + _11100101
    //   x16       = _11111111 << 8 + _11111111
    //   x32       = x16 << 16 + x16
    //   i133      = ((x32 << 48 + x16) << 16 + x16) << 16
    //   i158      = ((x16 + i133) << 16 + x16) << 6 + _101111
    //   i186      = ((i158 << 9 + _1110011) << 8 + _1111101) << 9
    //   i206      = ((_10101101 + i186) << 8 + _10100111) << 9 + _101111
    //   i236      = ((i206 << 8 + _111101) << 11 + _1001111) << 9
    //   i257      = ((_1110111 + i236) << 10 + _11100101) << 8 + _1100001
    //   i286      = ((i257 << 7 + _111111) << 10 + _1100011) << 10
    //   return      (_10010101 + i286) << 6 + _1111
    //
    // Operations: 251 squares and 43 multiplications.
    //
    // Generated by github.com/mmcloughlin/addchain v0.4.0.

    let mut t0;
    let mut t1;
    let mut t2;
    let mut t3;
    let mut t4;
    let mut t5;
    let mut t6;
    let mut t7;
    let mut t8;
    let mut t9;
    let mut t10;
    let mut t11;
    let mut t12;
    let mut t13;
    let mut t14;
    let mut z;

    // Step 1: t0 = x^0x2
    t0 = x.square();

    // Step 2: t1 = x^0x4
    t1 = t0.square();

    // Step 3: t2 = x^0x5
    t2 = x * t1;

    // Step 4: t3 = x^0x6
    t3 = x * t2;

    // Step 5: t4 = x^0x9
    t4 = t1 * t2;

    // Step 6: z = x^0xf
    z = t3 * t4;

    // Step 7: t5 = x^0x12
    t5 = t4.square();

    // Step 8: t6 = x^0x15
    t6 = t3 * z;

    // Step 9: t7 = x^0x18
    t7 = t3 * t5;

    // Step 10: t8 = x^0x1a
    t8 = t0 * t7;

    // Step 11: t6 = x^0x2f
    t6 *= t8;

    // Step 12: t4 = x^0x38
    t4 *= t6;

    // Step 13: t2 = x^0x3d
    t2 *= t4;

    // Step 14: t9 = x^0x3f
    t9 = t0 * t2;

    // Step 15: t10 = x^0x4f
    t10 = t5 * t2;

    // Step 16: t11 = x^0x61
    t11 = t5 * t10;

    // Step 17: t0 = x^0x63
    t0 *= t11;

    // Step 18: t12 = x^0x73
    t12 = t5 * t11;

    // Step 19: t1 = x^0x77
    t1 *= t12;

    // Step 20: t13 = x^0x7d
    t13 = t3 * t1;

    // Step 21: t7 = x^0x95
    t7 *= t13;

    // Step 22: t5 = x^0xa7
    t5 *= t7;

    // Step 23: t3 = x^0xad
    t3 *= t5;

    // Step 24: t4 = x^0xe5
    t4 *= t3;

    // Step 25: t8 = x^0xff
    t8 *= t4;

    // Step 33: t14 = x^0xff00
    t14 = t8.square();
    for _ in 1..8 {
        t14 = t14.square();
    }

    // Step 34: t8 = x^0xffff
    t8 *= t14;

    // Step 50: t14 = x^0xffff0000
    t14 = t8.square();
    for _ in 1..16 {
        t14 = t14.square();
    }

    // Step 51: t14 = x^0xffffffff
    t14 = t8 * t14;

    // Step 99: t14 = x^0xffffffff000000000000
    for _ in 0..48 {
        t14 = t14.square();
    }

    // Step 100: t14 = x^0xffffffff00000000ffff
    t14 = t8 * t14;

    // Step 116: t14 = x^0xffffffff00000000ffff0000
    for _ in 0..16 {
        t14 = t14.square();
    }

    // Step 117: t14 = x^0xffffffff00000000ffffffff
    t14 = t8 * t14;

    // Step 133: t14 = x^0xffffffff00000000ffffffff0000
    for _ in 0..16 {
        t14 = t14.square();
    }

    // Step 134: t14 = x^0xffffffff00000000ffffffffffff
    t14 = t8 * t14;

    // Step 150: t14 = x^0xffffffff00000000ffffffffffff0000
    for _ in 0..16 {
        t14 = t14.square();
    }

    // Step 151: t8 = x^0xffffffff00000000ffffffffffffffff
    t8 *= t14;

    // Step 157: t8 = x^0x3fffffffc00000003fffffffffffffffc0
    for _ in 0..6 {
        t8 = t8.square();
    }

    // Step 158: t8 = x^0x3fffffffc00000003fffffffffffffffef
    t8 = t6 * t8;

    // Step 167: t8 = x^0x7fffffff800000007fffffffffffffffde00
    for _ in 0..9 {
        t8 = t8.square();
    }

    // Step 168: t12 = x^0x7fffffff800000007fffffffffffffffde73
    t12 *= t8;

    // Step 176: t12 = x^0x7fffffff800000007fffffffffffffffde7300
    for _ in 0..8 {
        t12 = t12.square();
    }

    // Step 177: t13 = x^0x7fffffff800000007fffffffffffffffde737d
    t13 *= t12;

    // Step 186: t13 = x^0xffffffff00000000ffffffffffffffffbce6fa00
    for _ in 0..9 {
        t13 = t13.square();
    }

    // Step 187: t3 = x^0xffffffff00000000ffffffffffffffffbce6faad
    t3 *= t13;

    // Step 195: t3 = x^0xffffffff00000000ffffffffffffffffbce6faad00
    for _ in 0..8 {
        t3 = t3.square();
    }

    // Step 196: t5 = x^0xffffffff00000000ffffffffffffffffbce6faada7
    t5 *= t3;

    // Step 205: t5 = x^0x1fffffffe00000001ffffffffffffffff79cdf55b4e00
    for _ in 0..9 {
        t5 = t5.square();
    }

    // Step 206: t6 = x^0x1fffffffe00000001ffffffffffffffff79cdf55b4e2f
    t6 *= t5;

    // Step 214: t6 = x^0x1fffffffe00000001ffffffffffffffff79cdf55b4e2f00
    for _ in 0..8 {
        t6 = t6.square();
    }

    // Step 215: t2 = x^0x1fffffffe00000001ffffffffffffffff79cdf55b4e2f3d
    t2 *= t6;

    // Step 226: t2 = x^0xffffffff00000000ffffffffffffffffbce6faada7179e800
    for _ in 0..11 {
        t2 = t2.square();
    }

    // Step 227: t10 = x^0xffffffff00000000ffffffffffffffffbce6faada7179e84f
    t10 *= t2;

    // Step 236: t10 = x^0x1fffffffe00000001ffffffffffffffff79cdf55b4e2f3d09e00
    for _ in 0..9 {
        t10 = t10.square();
    }

    // Step 237: t1 = x^0x1fffffffe00000001ffffffffffffffff79cdf55b4e2f3d09e77
    t1 *= t10;

    // Step 247: t1 = x^0x7fffffff800000007fffffffffffffffde737d56d38bcf4279dc00
    for _ in 0..10 {
        t1 = t1.square();
    }

    // Step 248: t4 = x^0x7fffffff800000007fffffffffffffffde737d56d38bcf4279dce5
    t4 *= t1;

    // Step 256: t4 = x^0x7fffffff800000007fffffffffffffffde737d56d38bcf4279dce500
    for _ in 0..8 {
        t4 = t4.square();
    }

    // Step 257: t11 = x^0x7fffffff800000007fffffffffffffffde737d56d38bcf4279dce561
    t11 *= t4;

    // Step 264: t11 = x^0x3fffffffc00000003fffffffffffffffef39beab69c5e7a13cee72b080
    for _ in 0..7 {
        t11 = t11.square();
    }

    // Step 265: t9 = x^0x3fffffffc00000003fffffffffffffffef39beab69c5e7a13cee72b0bf
    t9 *= t11;

    // Step 275: t9 = x^0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc00
    for _ in 0..10 {
        t9 = t9.square();
    }

    // Step 276: t0 = x^0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc63
    t0 *= t9;

    // Step 286: t0 = x^0x3fffffffc00000003fffffffffffffffef39beab69c5e7a13cee72b0bf18c00
    for _ in 0..10 {
        t0 = t0.square();
    }

    // Step 287: t7 = x^0x3fffffffc00000003fffffffffffffffef39beab69c5e7a13cee72b0bf18c95
    t7 *= t0;

    // Step 293: t7 = x^0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632540
    for _ in 0..6 {
        t7 = t7.square();
    }

    // Step 294: z = x^0xffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc63254f
    z *= t7;

    z
}
